package io.github.susimsek.springdataaotsamples.web.error;

import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;

@Schema(name = "ProblemDetail", description = "Representation for an RFC 9457 problem detail")
public record ProblemDetail(
        @Schema(
                        description = "A URI reference that identifies the problem type",
                        example = "https://example.com/problem/validation_failed")
                String type,
        @Schema(
                        description = "Short, human-readable summary of the error",
                        example = "Validation Failed")
                String title,
        @Schema(description = "HTTP status code generated by the origin server", example = "400")
                Integer status,
        @Schema(
                        description =
                                "Detailed, human-readable explanation specific to this occurrence",
                        example = "One or more fields are invalid.")
                String detail,
        @Schema(
                        description = "A URI reference that identifies the specific occurrence",
                        example = "/api/v1/article/generate")
                String instance,
        @ArraySchema(arraySchema = @Schema(description = "Field-level validation failure details"))
                List<Violation> violations) {}
